# generated by datamodel-codegen:
#   filename:  opt_json.schema.json
#   timestamp: 2025-12-29T17:29:04+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class Int(RootModel[int]):
    root: int


class Number(RootModel[float]):
    root: float


class String(RootModel[str]):
    root: str


class Enum(RootModel[str | conint(ge=0)]):
    root: str | conint(ge=0)


class EnumArray(RootModel[list[Enum]]):
    root: list[Enum]


class Uuid(RootModel[UUID]):
    root: UUID


class Timestamp(RootModel[int]):
    root: int = Field(..., description="UNIX timestamp")


class ColorRgba(RootModel[constr(pattern=r"^#[0-9a-f]{6}([0-9a-f]{2})?$")]):
    root: constr(pattern=r"^#[0-9a-f]{6}([0-9a-f]{2})?$") = Field(
        ..., description="RGB(A) color in a standard hex notation '#RRGGBB(AA)'"
    )


class UnknownFieldsRegion(
    RootModel[
        dict[constr(pattern=r"^([0-9a-f]{2})+$"), constr(pattern=r"^([0-9a-f]{2})+$")]
    ]
):
    root: dict[constr(pattern=r"^([0-9a-f]{2})+$"), constr(pattern=r"^([0-9a-f]{2})+$")]


class Meta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    main_region_offset: Int | None = None
    main_region_size: Int | None = None
    aux_region_offset: Int | None = None
    aux_region_size: Int | None = None


class Main(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    instance_uuid: Uuid | None = None
    package_uuid: Uuid | None = None
    material_uuid: Uuid | None = None
    brand_uuid: Uuid | None = None
    gtin: Number | None = None
    brand_specific_instance_id: String | None = None
    brand_specific_package_id: String | None = None
    brand_specific_material_id: String | None = None
    material_class: Enum | None = None
    material_type: Enum | None = None
    material_name: String | None = None
    material_abbreviation: String | None = None
    brand_name: String | None = None
    write_protection: Enum | None = None
    manufactured_date: Timestamp | None = None
    country_of_origin: String | None = None
    expiration_date: Timestamp | None = None
    nominal_netto_full_weight: Number | None = None
    actual_netto_full_weight: Number | None = None
    nominal_full_length: Number | None = None
    actual_full_length: Number | None = None
    empty_container_weight: Number | None = None
    primary_color: ColorRgba | None = None
    secondary_color_0: ColorRgba | None = None
    secondary_color_1: ColorRgba | None = None
    secondary_color_2: ColorRgba | None = None
    secondary_color_3: ColorRgba | None = None
    secondary_color_4: ColorRgba | None = None
    transmission_distance: Number | None = None
    tags: EnumArray | None = None
    certifications: EnumArray | None = None
    density: Number | None = None
    filament_diameter: Number | None = None
    shore_hardness_a: Int | None = None
    shore_hardness_d: Int | None = None
    min_nozzle_diameter: Number | None = None
    min_print_temperature: Int | None = None
    max_print_temperature: Int | None = None
    preheat_temperature: Int | None = None
    min_bed_temperature: Int | None = None
    max_bed_temperature: Int | None = None
    min_chamber_temperature: Int | None = None
    max_chamber_temperature: Int | None = None
    chamber_temperature: Int | None = None
    container_width: Int | None = None
    container_outer_diameter: Int | None = None
    container_inner_diameter: Int | None = None
    container_hole_diameter: Int | None = None
    viscosity_18c: Number | None = None
    viscosity_25c: Number | None = None
    viscosity_40c: Number | None = None
    viscosity_60c: Number | None = None
    container_volumetric_capacity: Number | None = None
    cure_wavelength: Int | None = None


class Aux(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    consumed_weight: Number | None = None
    workgroup: String | None = None
    general_purpose_range_user: String | None = None
    last_stir_time: Timestamp | None = None


class Data(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    meta: Meta | None = None
    main: Main | None = None
    aux: Aux | None = None


class UnknownFields(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    meta: UnknownFieldsRegion | None = None
    main: UnknownFieldsRegion | None = None
    aux: UnknownFieldsRegion | None = None


class OpenprinttagJsonRepresentation(BaseModel):
    data: Data | None = Field(None, description="Decoded data on regions of the tag")
    unknown_fields: UnknownFields | None = Field(
        None,
        description="Fields that are not in the specification - specification mandates to preserve them. Kept as a key-value binary hex strings.",
    )
